### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by TheOnlyWayUp** [explosion/weasel#2]
Since this is now a public project, I would suggest improving upon the README to clearly explain what this package aims to do. This would give viewers and possible contributors a clear idea of what's expected.

:)

**Comment by adrianeboyd** [comment]
The README will be expanded in due time, opening an issue for this is not helpful.

**Comment by TheOnlyWayUp** [comment]
> The README will be expanded in due time, opening an issue for this is not helpful.

In that case, would you mind explaining to me the purpose of this project here? What does Weasel aim to achieve?

When having an open source project, I firmly believe in making the purpose of the project clear. This makes contributing and comparing easier.

**Comment by TheOnlyWayUp** [comment]
@adrianeboyd.
