### ISSUE TITLE
Migrating README in project from spacy projects to weasel

### ISSUE THREAD

**Issue by b2m** [explosion/weasel#41]
When migrating from *spacy projects* to *weasel* I noticed that `weasel document --output README.md` will replace the whole `README.md` (ignoring the hidden *spacy project* markers and removing additional content).

I guess this is OK as there is a warning on the CLI and you could recover lost information via version control.

But it would be more user friendly to offer to migrate the hidden *spacy project* markers and/or hint the incompatibility in the corresponding [README](https://github.com/explosion/weasel#migrating-from-spacy-projects) section of weasel.

**Comment by rmitsch** [comment]
Hey @b2m! Could you provide the readme (or a minimal version thereof) with the additional information that gets overwritten?

**Comment by b2m** [comment]
> Hey @b2m! Could you provide the readme (or a minimal version thereof) with the additional information that gets overwritten?

This is a zip file with a minimal `project.yml` and two README files showing the situation before and after migrating to weasel: [readme-example.zip](https://github.com/explosion/weasel/files/12080493/readme-example.zip)

**Content of `project.yml`:**
```yml
title: "Awesome project"
description: >
  Project using spacy projects and gets migrated to weasel.
```

**Steps to reproduce:**

0. Install spacy and weasel
1. Create `README.md` from `project.yml` via the following command should result in a file similar to `README_before.md` in the provided zip file (without additional content).
```bash
spacy project document --output README.md
```
2. Add more content **after** spacy projects auto generated docs marker (see `README_before.md` for an example).
3. Overwrite `README.md` via the following command should result in a file similar to `README_after.md` in the provided zip file.
```bash
weasel document --output README.md
```
Additional content added in step 2 is removed.

**Comment by rmitsch** [comment]
Thanks for the reproducible example! Yes, this is an inconsistency caused by the recent transition of the spaCy project management system to [`weasel`](https://github.com/explosion/weasel). We'll look into how to handle this better and will update here once we decide how to move forward.
