### ISSUE TITLE
Bump version for smart_open dependency

### ISSUE THREAD

**Issue by BLKSerene** [explosion/weasel#81]
Hi, `smart_open 7.0.1` has been released, are there any plans to support the new version? And the same for that dependency in `spaCy`.

**Comment by svlandeg** [comment]
Yes, we'll look into supporting the new version. Are there any breaking changes from 7.0.0 onwards, as far as you know? If you use `weasel` or `spacy` in an environment where you've already upgraded `smart_open` to the latest version, do you see any issues other than perhaps `pip` complaining about a potential conflict?

**Comment by BLKSerene** [comment]
Since I don't use the [project functionalities](https://spacy.io/usage/projects#data-assets-url) in `spaCy` or `weasel` directly, everything seems to be working fine with the latest `smart_open`.

**Comment by svlandeg** [comment]
Thanks for the confirmation! We'll get this pin updated.
